---
# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: gitpod/workspace-full

# Reference a Dockerfile next to your .gitpod.yml file
# Note: Currently, Gitpod only supports Debian/Ubuntu or Alpine based images.
# image:
#   file: .gitpod.Dockerfile

# Command to start on workspace startup (optional)
tasks:
  # Init task should only be executed after a workspace was freshly cloned
  # but not when restarting or starting a snapshot of that workspace.
  - init: go build -o goapp
    command: ./goapp

# Ports to expose on workspace startup (optional)
ports:
  - port: 8080
    onOpen: open-preview

# Extensions will be installed as listed here
vscode:
  extensions:
    - golang.go@0.16.2:KwEZ/3KscWWNBDyu17+5lw==#

# GitHub prebuild configuration
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false